
name = "todo-list-api2"
main = "main.ts"
compatibility_date = "2024-02-14"

[[durable_objects.bindings]]

name = "TODO_LIST"
class_name = "TodoListDO"

[[migrations]]

tag = "v1"
new_classes = ["TodoListDO"]

[site]

bucket = "./public"
